import type { HotelDesignation } from './hotelDesignations';

export type Zone = 'A' | 'B' | 'C' | 'D';

export interface BasicConfig {
  // For manual entry mode
  manualBasicAmount?: number;
  // For Tamil Nadu Hotel Rule mode (DA is now fixed, so only Basic percentage is needed)
  tnRuleBasicPercentage?: number;
}

// Default fallback configuration for designations without specific config
const DEFAULT_CONFIG: BasicConfig = {
  manualBasicAmount: 4210, // 50% of 8419
  tnRuleBasicPercentage: 50,
};

// Zone-wise designation to Basic configuration mapping
// Note: DA is now fixed at 8419 for all zones and designations
export const ZONE_DESIGNATION_CONFIG: Record<Zone, Partial<Record<HotelDesignation, BasicConfig>>> = {
  A: {
    // Management & Administration - Zone A (Premium)
    'General Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 55 },
    'Assistant General Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 55 },
    'Hotel Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 55 },
    'Assistant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Front Office Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Duty Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Night Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    
    // Front Office - Zone A
    'Front Desk Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Front Desk Agent': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Front Desk Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Receptionist': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Guest Relations Officer': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Concierge': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Bell Captain': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bellboy': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Door Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Valet Parking Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Housekeeping - Zone A
    'Housekeeping Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Assistant Housekeeping Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Housekeeping Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Room Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Housekeeping Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Linen Room Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Public Area Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Laundry Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Laundry Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Laundry Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Food & Beverage - Zone A
    'F&B Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Restaurant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Assistant Restaurant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Banquet Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Bar Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Captain': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Waiter': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Waitress': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Steward': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bartender': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Barista': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Sommelier': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Room Service Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Room Service Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Kitchen - Zone A
    'Executive Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 55 },
    'Sous Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Chef de Partie': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Demi Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis I': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis II': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis III': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Steward': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Helper': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Pastry Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Bakery Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    
    // Accounts & Finance - Zone A
    'Finance Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Accountant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Assistant Accountant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Accounts Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Accounts Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Cashier': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Night Auditor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Sales & Marketing - Zone A
    'Sales Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Sales Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Marketing Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Marketing Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Reservation Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Reservation Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Human Resources - Zone A
    'HR Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'HR Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Training Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Training Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Engineering & Maintenance - Zone A
    'Chief Engineer': { manualBasicAmount: 4210, tnRuleBasicPercentage: 52 },
    'Maintenance Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Maintenance Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Electrician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Plumber': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Carpenter': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'AC Technician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Maintenance Technician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Security - Zone A
    'Security Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Security Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Security Guard': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Other - Zone A
    'Spa Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Spa Therapist': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Fitness Instructor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Swimming Pool Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Driver': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Gardener': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
  },
  
  B: {
    // Management & Administration - Zone B
    'General Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 53 },
    'Assistant General Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 53 },
    'Hotel Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 53 },
    'Assistant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Front Office Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Duty Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Night Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    
    // Front Office - Zone B
    'Front Desk Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Front Desk Agent': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Front Desk Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Receptionist': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Guest Relations Officer': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Concierge': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bell Captain': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bellboy': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Door Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Valet Parking Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Housekeeping - Zone B
    'Housekeeping Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Assistant Housekeeping Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Housekeeping Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Room Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Housekeeping Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Linen Room Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Public Area Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Laundry Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Laundry Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Laundry Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Food & Beverage - Zone B
    'F&B Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Restaurant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Assistant Restaurant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Banquet Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Bar Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Captain': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Waiter': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Waitress': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Steward': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bartender': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Barista': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Sommelier': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Room Service Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Room Service Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Kitchen - Zone B
    'Executive Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 53 },
    'Sous Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Chef de Partie': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Demi Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis I': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis II': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis III': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Steward': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Helper': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Pastry Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bakery Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Accounts & Finance - Zone B
    'Finance Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Accountant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Assistant Accountant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Accounts Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Accounts Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Cashier': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Night Auditor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Sales & Marketing - Zone B
    'Sales Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Sales Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Marketing Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Marketing Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Reservation Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Reservation Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Human Resources - Zone B
    'HR Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'HR Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Training Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Training Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Engineering & Maintenance - Zone B
    'Chief Engineer': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Maintenance Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Maintenance Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Electrician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Plumber': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Carpenter': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'AC Technician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Maintenance Technician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Security - Zone B
    'Security Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Security Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Security Guard': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    
    // Other - Zone B
    'Spa Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Spa Therapist': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Fitness Instructor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Swimming Pool Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Driver': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Gardener': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
  },
  
  C: {
    // All designations in Zone C use default config
    'General Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Assistant General Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Hotel Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Assistant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Front Office Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Duty Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Night Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Front Desk Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Front Desk Agent': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Front Desk Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Receptionist': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Guest Relations Officer': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Concierge': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bell Captain': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bellboy': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Door Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Valet Parking Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Housekeeping Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Assistant Housekeeping Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Housekeeping Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Room Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Housekeeping Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Linen Room Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Public Area Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Laundry Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Laundry Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Laundry Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'F&B Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Restaurant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Assistant Restaurant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Banquet Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Bar Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Captain': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Waiter': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Waitress': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Steward': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bartender': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Barista': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Sommelier': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Room Service Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Room Service Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Executive Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Sous Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Chef de Partie': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Demi Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis I': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis II': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis III': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Steward': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Helper': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Pastry Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bakery Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Finance Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Accountant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Assistant Accountant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Accounts Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Accounts Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Cashier': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Night Auditor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Sales Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Sales Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Marketing Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Marketing Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Reservation Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Reservation Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'HR Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'HR Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Training Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Training Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Chief Engineer': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Maintenance Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Maintenance Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Electrician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Plumber': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Carpenter': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'AC Technician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Maintenance Technician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Security Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Security Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Security Guard': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Spa Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Spa Therapist': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Fitness Instructor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Swimming Pool Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Driver': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Gardener': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
  },
  
  D: {
    // All designations in Zone D use default config
    'General Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Assistant General Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Hotel Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Assistant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Front Office Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Duty Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Night Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Front Desk Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Front Desk Agent': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Front Desk Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Receptionist': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Guest Relations Officer': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Concierge': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bell Captain': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bellboy': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Door Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Valet Parking Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Housekeeping Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Assistant Housekeeping Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Housekeeping Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Room Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Housekeeping Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Linen Room Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Public Area Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Laundry Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Laundry Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Laundry Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'F&B Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Restaurant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Assistant Restaurant Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Banquet Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Bar Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Captain': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Waiter': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Waitress': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Steward': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bartender': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Barista': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Sommelier': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Room Service Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Room Service Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Executive Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Sous Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Chef de Partie': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Demi Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis I': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis II': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Commis III': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Steward': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Helper': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Kitchen Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Pastry Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Bakery Chef': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Finance Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Accountant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Assistant Accountant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Accounts Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Accounts Staff': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Cashier': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Night Auditor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Sales Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Sales Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Marketing Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Marketing Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Reservation Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Reservation Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'HR Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'HR Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Training Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Training Executive': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Chief Engineer': { manualBasicAmount: 4210, tnRuleBasicPercentage: 50 },
    'Maintenance Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Maintenance Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Electrician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Plumber': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Carpenter': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'AC Technician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Maintenance Technician': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Security Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Security Supervisor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Security Guard': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Spa Manager': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Spa Therapist': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Fitness Instructor': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Swimming Pool Attendant': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Driver': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
    'Gardener': { manualBasicAmount: 4210, tnRuleBasicPercentage: 48 },
  },
};

export function getBasicConfigForDesignation(
  zone: Zone,
  designation: HotelDesignation
): BasicConfig | null {
  return ZONE_DESIGNATION_CONFIG[zone][designation] || DEFAULT_CONFIG;
}
